### ISSUE TITLE
different results in khz

### ISSUE THREAD

**Issue by zeyunZhao** [wmglab-duke/axonml#1] opened 2024-10-06 14:11 UTC
hi, I have run your code successfully but I find that the results are different from that reported in your paper. Take khz as an example, the results generated by SMF are higher than MRG. I didn't change anything to your code except file paths. Could you tell me why?
![khz_stim_example0](https://github.com/user-attachments/assets/f48bea02-190f-4440-83a3-2b1f1e3e383c)

**Comment by minhajh** [comment] 2024-10-06 17:59
What versions of PyTorch, CUDA, and what model of GPU are you using?

**Comment by minhajh** [comment] 2024-10-06 23:27
This was caused by `APCount` erroneously counting certain APs twice. It should be fixed by eefe194.

**Closed** 2024-10-06 23:54 UTC

**Comment by zeyunZhao** [comment] 2024-10-07 02:20
> This was caused by `APCount` erroneously counting certain APs twice. It should be fixed by [eefe194](https://github.com/wmglab-duke/axonml/commit/eefe1940b4169d7eb9f5589cab0c525cb29ae05f).

Thanks for your reply. I got the same results after revising the codes
