### ISSUE TITLE
No "MRG" in axonml.models

### ISSUE THREAD

**Issue by zeyunZhao** [wmglab-duke/axonml#3] opened 2024-11-06 16:44 UTC
Hi, I'v been trying to reproduce your work.
 
I have run data generation codes successfully. But when I try to run training codes, there are many problems. 

Case 1: 
When I run python train.py, it showed that "ImportError: cannot import name 'MRG' from 'axonml.models'";  I checked the __inite__.py  in axonml.models, there is no MRG in it. 

The content in __inite__.py only has these three models. 
__all__ = ["Backend", "Axon", "SMF"]

from .backend import Backend

from .core import Axon
from .implementations import SMF

Case 2: 
When I change MRG to SMF, the model can run only 1 epoch, then it break down with the alarm: 
 "RuntimeError: The size of tensor a (0) must match the size of tensor b (32) at non-singleton dimension 0" .

I didn't change any content of your codes and followed your guidance written in the project. Could you help me out? 

Appreciate any reply!

**Comment by minhajh** [comment] 2024-11-06 17:39
Thanks for pointing out the import issue. Yes, 'SMF' should be imported rather than 'MRG'. This is fixed by 7cd1c1f. I cannot reproduce your second issue. Can you provide the complete output to your console? Have you tried running the training script with the example datasets (https://doi.org/10.7924/r48g8tf24)?

**Comment by zeyunZhao** [comment] 2024-11-06 19:13
Thanks for your reply. I can run it on example data but cannot run it on the data that I generated. I have attached the corresponding results. 

Results on example data: 

(axonml) [zeyun.zhao@c1007a-s23 axonml]$ CUDA_VISIBLE_DEVICES=7 python train.py 
  0%|▉                                                                                                                                                                                                                                                     | 1/256 [00:02<09:49,  2.31s/it, loss=242]
  0%|                                                                                                                                                                                                                                      | 1/2048 [01:51<63:25:20, 111.54s/it, cm=0.0101, loss=663]
  0%|▉                                                                                                                                                                                                                                                     | 1/256 [00:00<02:29,  1.70it/s, loss=243]
  0%|                                                                                                                                                                                                                                        | 1/2048 [00:02<1:37:17,  2.85s/it, cm=0.0103, loss=510]
  0%|▉                                                                                                                                                                                                                                                     | 1/256 [00:00<02:28,  1.72it/s, loss=232]
  0%|                                                                                                                                                                                                                                        | 1/2048 [00:02<1:17:08,  2.26s/it, cm=0.0104, loss=459]
  0%|▉                                                                                                                                                                                                                                                     | 1/256 [00:00<02:27,  1.73it/s, loss=227]
  0%|                                                                                                                                                                                                                                          | 1/2048 [00:01<50:38,  1.48s/it, cm=0.0104, loss=442]
  0%|▉                                                                                                                                                                                                                                                     | 1/256 [00:00<02:27,  1.73it/s, loss=222]
  0%|                                                                                                                                                                                                                                          | 1/2048 [00:01<50:40,  1.49s/it, cm=0.0105, loss=411
--------------------------------------------------------------------------------------------------------------------------------------------

Results on generated data:

(axonml) [zeyun.zhao@c1007a-s23 axonml]$ CUDA_VISIBLE_DEVICES=7 python train.py 
  0%|                                                                                                                                                                                                                                                  | 0/2048 [00:14<?, ?it/s, cm=0.0101, loss=585/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/training/data.py:100: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).256 [00:03<14:54,  3.51s/it]
  torch.tensor(diameters_chunk, device=self.device)
  1%|██                                                                                                                                                                                                                                                              | 2/256 [00:07<15:02,  3.55s/it]
  0%|                                                                                                                                                                                                                                                  | 0/2048 [00:21<?, ?it/s, cm=0.0101, loss=585]
Traceback (most recent call last):
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/train.py", line 61, in <module>
    tbptt(
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/training/bptt.py", line 125, in tbptt
    validation_error = validate(model, rec, val_dset, loss_fn)
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/training/bptt.py", line 241, in validate
    model.run(x, diams, dt=0.005, reinit=True, callbacks=[rec])
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/models/core.py", line 408, in run
    states = self.advance(ves, states, gbar, cm, ra, intra, dt, i)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/models/core.py", line 317, in fallback_function
    
        # -- calculate ionic current --
        i_ion = self.currents(states, gbar, i, intra)
                ~~~~~~~~~~~~~ <--- HERE
    
        # -- update vm --
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/models/core.py", line 260, in currents
        """
    
        c = self.ionic_currents(states, gbar)
            ~~~~~~~~~~~~~~~~~~~ <--- HERE
        if intra is not None:
            c -= intra[i]
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/models/implementations.py", line 276, in ionic_currents
        gnabar, gnapbar, gkbar, gl = gbar
        i_ion = (
            (gnabar[:, None, None] * m**3 * h * (vm - self.ena))
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            + (gnapbar[:, None, None] * p**3 * (vm - self.ena))
            + (gkbar[:, None, None] * s * (vm - self.ek))
RuntimeError: The size of tensor a (0) must match the size of tensor b (32) at non-singleton dimension 0

**Comment by zeyunZhao** [comment] 2024-11-06 19:24
![image](https://github.com/user-attachments/assets/257396df-bf71-46e4-b44f-6cc9884b3e66)

**Comment by zeyunZhao** [comment] 2024-11-06 19:38
But I didn't change any parameters when I run generate_data.py and consolidate_data.py

**Comment by minhajh** [comment] 2024-11-06 20:00
This error is arising in the 'validate' function. Did you generate a validation dataset? What are those dimensions?

**Comment by zeyunZhao** [comment] 2024-11-06 20:07
I just use the same data to do the validation

**Comment by zeyunZhao** [comment] 2024-11-06 20:07
# # training / validation data locations
train_dset = "/orange/ruogu.fang/zeyun.zhao/consolidated_data_train"
valid_dset = "/orange/ruogu.fang/zeyun.zhao/consolidated_data_train"

**Comment by zeyunZhao** [comment] 2024-11-06 20:28
I also tried not to use val_data in training, but still got the similar error. 

In train.py, I didn't feed val_data:
tbptt(
        model,
        train_data,
        loss,
        optimizer,
        config.epochs,
        config.truncation_length,
        config.dt,
        config.grad_accumulation,
        config.postfix,
        config.save_every,
        config.save_dir,
        # val_data,      # this line I changed
    )

When I train it without val_data, the codes can run in example data but failed again in generated data with the results as follows:

(axonml) [zeyun.zhao@c1007a-s23 axonml]$ CUDA_VISIBLE_DEVICES=7 python train.py 
  0%|                                                                                                                                                                                                                                                    | 0/2048 [00:07<?, ?it/s, cm=0.01, loss=nan]
Traceback (most recent call last):
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/train.py", line 61, in <module>
    tbptt(
  File "/home/zeyun.zhao/vscode/code/VNS/axonml_0/axonml/training/bptt.py", line 126, in tbptt
    train_error = cum_loss / n
ZeroDivisionError: division by zero

**Comment by minhajh** [comment] 2024-11-06 20:51
The ZeroDivisionError is because the evaluated loss was NaN and so no losses have actually been accumulated. You can try to instantiate the model with `handle_nan=True` (edit train.py) to see if that helps. Also increase 'save_every' from 1 in config.py as it's probably not necessary to validate & record the model parameters after every minibatch. Another thing to check is depending on the version of MPI against which you built parallel hdf5 there may be numerical errors in your dataset which could also cause the model to return NaN values. I don't know why there's a size mismatch when you try to validate with your generated dataset, but it would be helpful to see if you can complete a training epoch without validation.

**Comment by zeyunZhao** [comment] 2024-11-06 21:20
I think the problem probably appears in consolidate_data.py. 

ys = new.create_dataset(
            "ys", (len(keys), sample_size, n_axons), chunks=(1, sample_size, n_axons)
        )
 d = new.create_dataset(
            "diameters",
            (len(keys), sample_size, n_axons),
            chunks=(1, sample_size, n_axons),
        )

Could you check if these two lines are correct. 

When I print the data you provided in example data, their sizes are (1,32,32), and they have the same numbers in the second and the third channels. But when I generate data by myself, they have different numbers.

**Comment by zeyunZhao** [comment] 2024-11-06 21:20
![image](https://github.com/user-attachments/assets/4a26f060-9a44-4d06-9ad0-f1c643cc1a5e)

**Comment by zeyunZhao** [comment] 2024-11-06 21:25
In data generation. When I set config as: 

# size of dataset
n_batches = 1
batch_size = 1
axons_per_minibatch = 32

the results are: 

Datasets in the HDF5 file:
activations :    (1, 1, 32)
diameters :    (1, 1, 32)
e :    (1, 1, 32, 53, 1001)
h :    (1, 1, 32, 53, 1001)
m :    (1, 1, 32, 53, 1001)
p :    (1, 1, 32, 53, 1001)
parameters :    (64, 32, 64)
s :    (1, 1, 32, 53, 1001)
v :    (1, 1, 32, 53, 1001)
ys :    (1, 1, 32)

But your example data are:

Datasets in the HDF5 file:
activations :    (1, 1, 32)
diameters :    (1, 32, 32)
e :    (1, 1, 32, 53, 1001)
h :    (1, 1, 32, 53, 1001)
m :    (1, 1, 32, 53, 1001)
p :    (1, 1, 32, 53, 1001)
parameters :    (1, 1, 64)
s :    (1, 1, 32, 53, 1001)
v :    (1, 1, 32, 53, 1001)
ys :    (1, 32, 32)


the shape of diameters and ys are different between the data generated by consolidate_data.py and your example data.

**Comment by zeyunZhao** [comment] 2024-11-06 21:28
In data generation. When I set config as:

size of dataset
n_batches = 1
batch_size = 1
axons_per_minibatch = 32

the results are:

Datasets in the HDF5 file:
activations : (1, 1, 32)
diameters : (1, 1, 32)
e : (1, 1, 32, 53, 1001)
h : (1, 1, 32, 53, 1001)
m : (1, 1, 32, 53, 1001)
p : (1, 1, 32, 53, 1001)
parameters : (1, 1, 64)
s : (1, 1, 32, 53, 1001)
v : (1, 1, 32, 53, 1001)
ys : (1, 1, 32)

But your example data are:

Datasets in the HDF5 file:
activations : (1, 1, 32)
diameters : (1, 32, 32)
e : (1, 1, 32, 53, 1001)
h : (1, 1, 32, 53, 1001)
m : (1, 1, 32, 53, 1001)
p : (1, 1, 32, 53, 1001)
parameters : (1, 1, 64)
s : (1, 1, 32, 53, 1001)
v : (1, 1, 32, 53, 1001)
ys : (1, 32, 32)

the shape of diameters and ys are different between the data generated by consolidate_data.py and your example data.

in generated data:
diameters : (1, 1, 32) / ys : (1, 1, 32)

in example data:
diameters : (1, 32, 32) / ys : (1, 32, 32)

**Comment by zeyunZhao** [comment] 2024-11-06 21:31
When I set batch_size=1 and repeat diameters and ys's third channel to transfer them from [n,1,32] --> [n,32,32], the code can work well

**Comment by zeyunZhao** [comment] 2024-11-06 21:32
So, What if I set batch_size>1, how should I generate the diameters and ys?

**Comment by minhajh** [comment] 2024-11-07 17:13
No, if you set batch_size=1 it should generate a dataset where diameters has shape (1, 1, 32). Can you check what the shapes of gnabar and m are (add print statements before the line that raises the error). Can you also share what version of PyTorch you are using.

**Comment by zeyunZhao** [comment] 2024-11-07 19:06
Pytorch:  

torch               1.13.1
torchaudio          0.13.1
torchvision         0.14.1

Cuda: 11.6
------------------------------------------------------------------------------------------------------------
Datageneration config:  (the parameter I changed) 

--size of dataset
n_batches = 1
batch_size = 32
axons_per_minibatch = 32

------------------------------------------------------------------------------------------------------------
format of generated data: 

Datasets in the HDF5 file:
activations :    (1, 32, 32)
diameters :    (1, 32, 32)
e :    (1, 32, 32, 53, 1001)
h :    (1, 32, 32, 53, 1001)
m :    (1, 32, 32, 53, 1001)
p :    (1, 32, 32, 53, 1001)
parameters :    (1, 32, 64)
s :    (1, 32, 32, 53, 1001)
v :    (1, 32, 32, 53, 1001)
ys :    (1, 32, 32)

------------------------------------------------------------------------------------------------------------

def ionic_currents(self, states: List[Tensor], gbar: List[Tensor]):
        m, h, p, s, vm = states
        gnabar, gnapbar, gkbar, gl = gbar
        print("gbar:  len:  ", len(gbar), "  ", [k.shape for k in gbar])
        print("m:  ", m.shape)

        i_ion = (
            (gnabar[:, None, None] * m**3 * h * (vm - self.ena))
            + (gnapbar[:, None, None] * p**3 * (vm - self.ena))
            + (gkbar[:, None, None] * s * (vm - self.ek))
            + (gl[:, None, None] * (vm - self.el))
        )  # mA
        return i_ion
------------------------------------------------------------------------------------------------------------
sizes of gbar and m:

epoch 1: 

gbar:  len:   4    [[32], [32], [32], [32]]
m:   [32, 1, 53]

epoch 2: 

gbar:  len:   4    [[1], [1], [1], [1]]
m:   [32, 1, 53]

epoch 3: 

gbar:  len:   4    [[0], [0], [0], [0]]
m:   [32, 1, 53]

then the program broke down

**Comment by zeyunZhao** [comment] 2024-11-07 19:20
![image](https://github.com/user-attachments/assets/1e3abc3f-29f3-4601-9e59-7936e7d07551)

When I print the parameters that have been fed into self.advance(), I find "ra" and "cm" are none. 

states, ves = self.prepare_inputs(self.n_states, ic, ve)        # states: 5*[torch.Size([32, 1, 53]);  ves: 50*torch.Size([32, 1, 53])
            cm, ra, gbar = self.prepare_parameters(diameters)               # cm:32* torch.Size([]);  ra: 32* torch.Size([]); gbar: 4*[torch.Size([32])]

**Comment by minhajh** [comment] 2024-11-07 19:26
What is the shape of "diameters"?

**Comment by zeyunZhao** [comment] 2024-11-07 19:30
torch.Size([32])

**Comment by zeyunZhao** [comment] 2024-11-07 19:30
diameters: torch.Size([32])

**Comment by minhajh** [comment] 2024-11-07 19:35
For every 'epoch'? (Really minibatch per epoch). Have you made any edits to your config.py or axonml/training/data.py?

**Comment by zeyunZhao** [comment] 2024-11-07 20:23
![image](https://github.com/user-attachments/assets/cf12d6ac-8909-44bd-8141-3e5eb7d6f990)

for config.py, I just change / validation data locations. 

for axonml/training/data.py?, I didn't change anything. 

for diameters, it changes from 32 --> 1 --> 0

**Comment by zeyunZhao** [comment] 2024-11-07 20:24
here is the changes of diameters 
![image](https://github.com/user-attachments/assets/66526f6a-7626-4885-985c-77a842e33b06)

**Comment by minhajh** [comment] 2024-11-07 20:43
PyTorch is under the impression that `diameters_chunk` is a tensor, when it should by a NumPy array. `diameters_chunk` is only declared in `axonml/training/data.py`. Do you have any other versions of axonml on your $PYTHONPATH that may have edits to `axonml/training/data.py`?

**Comment by zeyunZhao** [comment] 2024-11-07 20:50
![image](https://github.com/user-attachments/assets/1f47321f-1982-4b68-ae4e-61a4d3ef636d)

**Comment by zeyunZhao** [comment] 2024-11-07 20:51
it seems like I have two axonml in sys.path

**Comment by minhajh** [comment] 2024-11-07 20:54
The UserWarning is being triggered on line 221 of `axonml_0/axonml/training/data.py`. The file on GitHub has only 118 lines, suggesting substantial edits.

**Comment by minhajh** [comment] 2024-11-07 21:08
Can you post the contents of your `train.py`?

**Comment by zeyunZhao** [comment] 2024-11-07 21:09
import h5py
import torch

import sys
sys.path.append("/home/zeyun.zhao/vscode/code/VNS/cajal")
sys.path.append("/home/zeyun.zhao/vscode/code/VNS/axonml_0")

import config
from axonml.models import Axon
from axonml.training import tbptt, DataLoader


def collect_states(h5py_file, states):
    return [h5py_file[s] for s in states]


dset_t = h5py.File(config.train_dset, "r")
dset_v = h5py.File(config.valid_dset, "r")


if __name__ == "__main__":
    if not config.fp32:
        torch.set_default_dtype(torch.float64)

    model: Axon = config.model(fp32=config.fp32)
    optimizer = torch.optim.Adam(model.parameters(), lr=config.lr)
    loss = torch.nn.MSELoss()

    if config.cuda:
        model = model.cuda()
        loss = loss.cuda()

    for p in config.to_train:
        model.unfreeze(p)

    train_data = DataLoader(
        config.nodes,
        dset_t["e"],
        collect_states(dset_t, config.states),
        dset_t["diameters"],
        config.train_n_idx,
        config.train_chunk_size,
        config.sampling,
        model.device(),
        config.fp32,
    )

    val_data = DataLoader(
        config.nodes,
        dset_v["e"],
        collect_states(dset_v, config.states),
        dset_v["diameters"],
        config.val_n_idx,
        config.val_chunk_size,
        config.sampling,
        model.device(),
        config.fp32,
    )

    

    # perform training
    tbptt(
        model,
        train_data,
        loss,
        optimizer,
        config.epochs,
        config.truncation_length,
        config.dt,
        config.grad_accumulation,
        config.postfix,
        config.save_every,
        config.save_dir,
        val_data,
        # handle_nan=True
    )

**Comment by zeyunZhao** [comment] 2024-11-07 21:26
I see. When I install the environments, I followed both cajal and axonml. Will it influence the results? Am I supposed to reinstall them just follow the guidance of Axonml?

**Comment by zeyunZhao** [comment] 2024-11-07 21:36
thank you so much. It seems like that I met the same question that I met yesterday. 

![image](https://github.com/user-attachments/assets/11c7b46c-d820-4633-ab6f-5de73cbb26b1)

Can I change it with 

train_error = cum_loss / (n+1e-5)?

**Comment by minhajh** [comment] 2024-11-07 21:45
This can be a more subtle issue. You _can_ change the denominator to (n + 1e-5), but actually ensuring that your model trains will involve checking that your training data is healthy (as I said in a previous reply, depending on the version of MPI against which you built your parallel hdf5 you could have weird floating point values in your training data that will cause the model to predict NaN), checking that you have an adequate batch size for your data; there may also be differences in the arithmetic between versions of PyTorch. I'm going to close this issue; further discussion about model training will be best done in the "Discussions" page.

**Closed by minhajh** 2024-11-07 21:45 UTC
